"""Structured metadata specs for guided artifact catalogs."""

from __future__ import annotations

TRAINING_START_HERE_LINES = [
    "# Buradan Başla",
    "",
    "Ham artefact dosyaları korunur. Önce şu sırayı izleyin:",
    "",
    "1. `guided/01_run_overview.json`",
    "2. `production_readiness.json`",
    "3. `training/summary.json`",
    "4. `test/metric_gate.json`",
    "5. `ood_benchmark/summary.json` veya `test/ood_evidence_summary.json`",
    "",
    "Tanı için:",
    "- `guided/10_training.md`",
    "- `guided/20_validation.md`",
    "- `guided/30_test.md`",
    "- `guided/40_ood_and_readiness.md`",
    "- `guided/50_adapter_export.md`",
    "- `guided/60_logs_and_checkpoints.md`",
    "",
    "Katalog tabanı: `{catalog_base}`",
    "",
]

PREP_START_HERE_LINES = [
    "# Buradan Başla",
    "",
    "Notebook 0 çıktılarında hiçbir ham dosya silinmez. Önce şu sırayla ilerleyin:",
    "",
    "1. `guided/01_prep_overview.json`",
    "2. `prep_summary.json`",
    "3. `proposed_split_manifest.json`",
    "4. `cross_class_conflicts.csv` ve `same_class_high_risk_clusters.csv`",
    "",
    "Katalog tabanı: `{catalog_base}`",
    "",
]

TRAINING_CATEGORY_DOCS = {
    "training": ("10_training.md", "Eğitim Dosyaları", "Bu bölüm eğitim geçmişi ve eğri dosyalarını özetler."),
    "validation": ("20_validation.md", "Validation Dosyaları", "Bu bölüm validation split artefactlerini toplar."),
    "test": ("30_test.md", "Test Dosyaları", "Bu bölüm held-out test artefactlerini toplar."),
    "ood_and_readiness": (
        "40_ood_and_readiness.md",
        "OOD ve Readiness",
        "Bu bölüm OOD kanıtı ve nihai readiness kararını toplar.",
    ),
    "adapter_export": (
        "50_adapter_export.md",
        "Adapter Export",
        "Bu bölüm adapter export ve notebook export dosyalarını listeler.",
    ),
    "logs_and_checkpoints": (
        "60_logs_and_checkpoints.md",
        "Log ve Checkpoint",
        "Bu bölüm runtime logları ve checkpoint kayıtlarını listeler.",
    ),
}

PREP_CATEGORY_DOCS = {
    "summary": ("10_summary.md", "Prep Özeti", "Ana prep özeti ve koşu görünümü."),
    "label_normalization": (
        "20_label_normalization.md",
        "Etiket Normalizasyonu",
        "Ham sınıf isimlerinin normalize sonuçları.",
    ),
    "class_health": ("30_class_health.md", "Sınıf Sağlığı", "Sınıf bazlı risk ve dağılım raporları."),
    "split_plan": ("40_split_plan.md", "Split Planı", "Önerilen split ve OOD handoff kararları."),
    "review_items": ("50_review_items.md", "İnceleme Öğeleri", "Manuel inceleme gerektiren çift ve kümeler."),
    "manifests": ("60_manifests.md", "Manifestler", "Tam veri ve aile manifestleri."),
}

TRAINING_STATIC_ENTRY_SPECS = [
    {
        "relative_path": "production_readiness.json",
        "category": "ood_and_readiness",
        "priority": "critical",
        "title_tr": "Nihai üretim hazırlığı kararı",
        "description_tr": "Deploy kararı için önce bakılması gereken ana dosya.",
        "reader_goal": "Modelin üretime çıkmaya hazır olup olmadığını anlamak",
        "decision_importance": "deploy_decision",
        "read_order": 1,
    },
    {
        "relative_path": "training/summary.json",
        "category": "training",
        "priority": "critical",
        "title_tr": "Eğitim özeti",
        "description_tr": "Koşunun kimliği, sınıfları, temel metrikleri ve export yollarını özetler.",
        "reader_goal": "Koşunun ne ürettiğini tek dosyada görmek",
        "decision_importance": "run_overview",
        "read_order": 2,
    },
    {
        "relative_path": "test/metric_gate.json",
        "category": "test",
        "priority": "critical",
        "title_tr": "Test gate özeti",
        "description_tr": "Held-out test performansının gate kararını içerir.",
        "reader_goal": "Asıl test kararını görmek",
        "decision_importance": "deploy_decision",
        "read_order": 3,
    },
    {
        "relative_path": "validation/metric_gate.json",
        "category": "validation",
        "priority": "high",
        "title_tr": "Validation gate özeti",
        "description_tr": "Validation split üzerinde ölçülen yardımcı gate kararı.",
        "reader_goal": "Test öncesi referans performansı görmek",
        "decision_importance": "supporting_diagnostic",
        "read_order": 4,
    },
    {
        "relative_path": "ood_benchmark/summary.json",
        "category": "ood_and_readiness",
        "priority": "high",
        "title_tr": "OOD benchmark özeti",
        "description_tr": "Gerçek OOD yoksa kullanılan held-out benchmark sonucunu özetler.",
        "reader_goal": "OOD fallback kanıtını incelemek",
        "decision_importance": "ood_decision",
        "read_order": 5,
    },
    {
        "relative_path": "training/history.json",
        "category": "training",
        "priority": "high",
        "title_tr": "Epoch bazlı eğitim geçmişi",
        "description_tr": "Epoch seviyesinde loss ve performans eğrilerini JSON olarak saklar.",
        "reader_goal": "Eğitim trendini programatik olarak incelemek",
        "decision_importance": "training_diagnosis",
        "read_order": 10,
    },
    {
        "relative_path": "training/history.csv",
        "category": "training",
        "priority": "medium",
        "title_tr": "Eğitim geçmişi CSV",
        "description_tr": "Epoch metriklerinin tablo formatındaki karşılığı.",
        "reader_goal": "Tablo halinde eğitim eğrilerini incelemek",
        "decision_importance": "training_diagnosis",
        "read_order": 11,
    },
    {
        "relative_path": "training/results.csv",
        "category": "training",
        "priority": "medium",
        "title_tr": "Eğitim sonuç tablosu",
        "description_tr": "Özet epoch sonuçlarını CSV halinde sunar.",
        "reader_goal": "Epoch sonuçlarını hızlıca taramak",
        "decision_importance": "training_diagnosis",
        "read_order": 12,
    },
    {
        "relative_path": "training/batch_metrics.csv",
        "category": "training",
        "priority": "medium",
        "title_tr": "Batch metrikleri",
        "description_tr": "Adım bazlı loss, LR ve throughput kayıtlarını içerir.",
        "reader_goal": "İnce taneli eğitim davranışını incelemek",
        "decision_importance": "training_diagnosis",
        "read_order": 13,
    },
    {
        "relative_path": "training/results.png",
        "category": "training",
        "priority": "medium",
        "title_tr": "Eğitim grafik paneli",
        "description_tr": "Loss, accuracy ve throughput eğrilerini tek görselde toplar.",
        "reader_goal": "Eğitimin genel seyrini görsel olarak görmek",
        "decision_importance": "training_diagnosis",
        "read_order": 14,
    },
    {
        "relative_path": "ood_benchmark/per_fold.csv",
        "category": "ood_and_readiness",
        "priority": "medium",
        "title_tr": "OOD benchmark fold tablosu",
        "description_tr": "Held-out benchmark fold sonuçlarını tek tabloda toplar.",
        "reader_goal": "Fold bazında OOD performansını incelemek",
        "decision_importance": "ood_decision",
        "read_order": 50,
    },
    {
        "relative_path": "ood_benchmark/progress.json",
        "category": "ood_and_readiness",
        "priority": "low",
        "title_tr": "OOD benchmark ilerleme kaydı",
        "description_tr": "Uzun benchmark çalışırken ara durum bilgisini tutar.",
        "reader_goal": "Benchmark sürecinin hangi aşamada kaldığını görmek",
        "decision_importance": "runtime_diagnostic",
        "read_order": 51,
    },
]

TRAINING_CURVE_GLOB_SPEC = {
    "glob": "training/training_curves*.png",
    "category": "training",
    "priority": "low",
    "title_template": "Eğitim eğrisi görseli: {name}",
    "description_tr": "Notebook tarafından ara/final aşamada kaydedilen eğitim eğrisi görseli.",
    "reader_goal": "Belirli epoch anlarındaki eğitim eğrilerini görmek",
    "decision_importance": "training_diagnosis",
    "read_order": 20,
}

TRAINING_SPLIT_ORDER_BASES = {"validation": 30, "test": 40}

TRAINING_SPLIT_ENTRY_SPECS = [
    {
        "relative_path": "{split}/classification_report.txt",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} sınıflandırma raporu",
        "description_tr": "Precision, recall ve F1 özetini metin formatında sunar.",
        "reader_goal": "Sınıf bazlı metrikleri metin olarak okumak",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 0,
    },
    {
        "relative_path": "{split}/classification_report.json",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} sınıflandırma raporu JSON",
        "description_tr": "Aynı raporun makine-okur JSON sürümü.",
        "reader_goal": "Raporu programatik olarak tüketmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 1,
    },
    {
        "relative_path": "{split}/per_class_metrics.csv",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} sınıf bazlı metrikler",
        "description_tr": "Her sınıf için precision, recall, F1 ve support değerlerini içerir.",
        "reader_goal": "Hangi sınıfta sorun olduğunu görmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 2,
    },
    {
        "relative_path": "{split}/confusion_matrix.csv",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} confusion matrix CSV",
        "description_tr": "Ham confusion matrix değerlerini tablo halinde tutar.",
        "reader_goal": "Karışan sınıf çiftlerini sayısal görmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 3,
    },
    {
        "relative_path": "{split}/confusion_matrix.png",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} confusion matrix görseli",
        "description_tr": "Ham confusion matrix'in görsel hali.",
        "reader_goal": "Hangi sınıfların karıştığını hızlı görmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 4,
    },
    {
        "relative_path": "{split}/confusion_matrix_normalized.png",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} normalize confusion matrix",
        "description_tr": "Sınıf büyüklüğünden bağımsız normalize confusion matrix görseli.",
        "reader_goal": "Oransal hata desenini görmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 5,
    },
    {
        "relative_path": "{split}/ood_type_breakdown.json",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} OOD tip kırılımı",
        "description_tr": "OOD klasör alt tiplerine göre metrik kırılımını içerir.",
        "reader_goal": "Hangi OOD alt tipinde sorun olduğunu görmek",
        "decision_importance": "ood_decision",
        "read_order_offset": 6,
    },
    {
        "relative_path": "{split}/ood_method_comparison.json",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} OOD method comparison",
        "description_tr": "Pooled ve slice-aware OOD score yöntem karşılaştırmasını içerir.",
        "reader_goal": "Ensemble, energy ve knn kanıtlarını karşılaştırmak",
        "decision_importance": "ood_decision",
        "read_order_offset": 7,
    },
    {
        "relative_path": "{split}/ood_evidence_summary.json",
        "category": "{split}",
        "priority": "high",
        "title_tr": "{split_title} OOD kanıt özeti",
        "description_tr": "Bu split için OOD örnek sayıları ve özet metrikleri gösterir.",
        "reader_goal": "OOD kanıtının yeterliliğini görmek",
        "decision_importance": "ood_decision",
        "read_order_offset": 7,
    },
    {
        "relative_path": "{split}/predictions.csv",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} sample predictions",
        "description_tr": "Her örnek için tahmin, etiket ve güven bilgisini CSV olarak sunar.",
        "reader_goal": "Yanlış tahmin edilen örnekleri tek tek incelemek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 8,
    },
    {
        "relative_path": "{split}/hard_examples.csv",
        "category": "{split}",
        "priority": "high",
        "title_tr": "{split_title} hard examples",
        "description_tr": "Yanlış sınıflanan veya kaçırılan OOD örneklerini öncelikli inceleme için listeler.",
        "reader_goal": "Feedback ile düzeltilecek zor örnekleri önceliklendirmek",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 9,
    },
    {
        "relative_path": "{split}/hard_examples_thumbnails",
        "category": "{split}",
        "priority": "medium",
        "title_tr": "{split_title} hard example thumbnails",
        "description_tr": "Zor örneklerin hızlı gözden geçirme için küçük önizlemelerini tutar.",
        "reader_goal": "Zor örnekleri görsel olarak hızlıca taramak",
        "decision_importance": "quality_diagnosis",
        "read_order_offset": 10,
    },
]

TRAINING_FOLD_ENTRY_SPECS = [
    {
        "filename": "metric_gate.json",
        "priority": "low",
        "title_template": "OOD fold gate özeti: {fold_name}",
        "description_template": "Held-out fold '{fold_name}' için üretilen yardımcı artefact.",
        "reader_goal": "Tek bir fold özelinde ayrıntı incelemek",
        "decision_importance": "ood_decision",
        "read_order": 60,
    },
    {
        "filename": "failure.json",
        "priority": "high",
        "title_template": "OOD fold hata özeti: {fold_name}",
        "description_template": "Held-out fold '{fold_name}' için üretilen yardımcı artefact.",
        "reader_goal": "Tek bir fold özelinde ayrıntı incelemek",
        "decision_importance": "runtime_diagnostic",
        "read_order": 61,
    },
    {
        "filename": "failure_traceback.txt",
        "priority": "high",
        "title_template": "OOD fold traceback: {fold_name}",
        "description_template": "Held-out fold '{fold_name}' için üretilen yardımcı artefact.",
        "reader_goal": "Tek bir fold özelinde ayrıntı incelemek",
        "decision_importance": "runtime_diagnostic",
        "read_order": 62,
    },
]

PREP_ENTRY_SPECS = [
    {
        "relative_path": "prep_summary.json",
        "category": "summary",
        "priority": "critical",
        "title_tr": "Prep ana özeti",
        "description_tr": "Notebook 0 koşusunun en önemli audit özetini içerir.",
        "reader_goal": "Dataset prep sonucunu tek dosyada görmek",
        "decision_importance": "prep_gate",
        "read_order": 1,
    },
    {
        "relative_path": "proposed_split_manifest.json",
        "category": "split_plan",
        "priority": "critical",
        "title_tr": "Önerilen split manifesti",
        "description_tr": "Her görüntünün hangi split'e gideceğini ve blokajları içerir.",
        "reader_goal": "Gerçek split planını incelemek",
        "decision_importance": "prep_gate",
        "read_order": 2,
    },
    {
        "relative_path": "ood_handoff_checklist.json",
        "category": "split_plan",
        "priority": "high",
        "title_tr": "OOD handoff kontrol listesi",
        "description_tr": "Prep sonrası OOD veri hazırlığı için kalan adımları gösterir.",
        "reader_goal": "OOD tarafında ne eksik olduğunu görmek",
        "decision_importance": "prep_gate",
        "read_order": 3,
    },
    {
        "relative_path": "label_normalization_report.json",
        "category": "label_normalization",
        "priority": "high",
        "title_tr": "Etiket normalizasyon raporu",
        "description_tr": "Ham sınıf klasör adlarının normalize sınıf adlarına nasıl eşlendiğini gösterir.",
        "reader_goal": "Sınıf isimlerinin doğru yorumlandığını doğrulamak",
        "decision_importance": "data_quality",
        "read_order": 10,
    },
    {
        "relative_path": "class_health_report.json",
        "category": "class_health",
        "priority": "high",
        "title_tr": "Sınıf sağlık raporu",
        "description_tr": "Her sınıfın aile sayısı, hedef split dağılımı ve risk özetini içerir.",
        "reader_goal": "Hangi sınıfların kırılgan olduğunu görmek",
        "decision_importance": "data_quality",
        "read_order": 11,
    },
    {
        "relative_path": "dataset_manifest.csv",
        "category": "manifests",
        "priority": "medium",
        "title_tr": "Tüm görüntü manifesti",
        "description_tr": "Taranan tüm görüntülerin kalite ve hash alanlarını içerir.",
        "reader_goal": "Ham veri kayıtlarını tablo halinde incelemek",
        "decision_importance": "data_audit",
        "read_order": 20,
    },
    {
        "relative_path": "family_manifest.csv",
        "category": "manifests",
        "priority": "medium",
        "title_tr": "Aile manifesti",
        "description_tr": "Görüntü aileleri ve split atamalarını satır bazında gösterir.",
        "reader_goal": "Aile bazlı grouping sonucunu görmek",
        "decision_importance": "data_audit",
        "read_order": 21,
    },
    {
        "relative_path": "same_class_review_candidates.csv",
        "category": "review_items",
        "priority": "medium",
        "title_tr": "Aynı sınıf inceleme adayları",
        "description_tr": "Borderline benzerlik gösteren aynı sınıf görüntü çiftleri.",
        "reader_goal": "Manuel inceleme gerektiren çiftleri görmek",
        "decision_importance": "data_quality",
        "read_order": 30,
    },
    {
        "relative_path": "same_class_review_clusters.csv",
        "category": "review_items",
        "priority": "medium",
        "title_tr": "Aynı sınıf inceleme kümeleri",
        "description_tr": "Manuel veya otomatik çözüm için gruplanmış review kümeleri.",
        "reader_goal": "Review işini küme bazında organize etmek",
        "decision_importance": "data_quality",
        "read_order": 31,
    },
    {
        "relative_path": "same_class_auto_resolved_clusters.csv",
        "category": "review_items",
        "priority": "low",
        "title_tr": "Otomatik çözülen review kümeleri",
        "description_tr": "Düşük riskli olduğu için otomatik çözülen kümeler.",
        "reader_goal": "Hangi review kümelerinin otomatik kapandığını görmek",
        "decision_importance": "data_quality",
        "read_order": 32,
    },
    {
        "relative_path": "same_class_high_risk_clusters.csv",
        "category": "review_items",
        "priority": "high",
        "title_tr": "Yüksek riskli review kümeleri",
        "description_tr": "Manuel kontrol gerektiren yüksek risk kümeleri.",
        "reader_goal": "Öncelikli insan inceleme listesini görmek",
        "decision_importance": "prep_gate",
        "read_order": 33,
    },
    {
        "relative_path": "cross_class_conflicts.csv",
        "category": "review_items",
        "priority": "critical",
        "title_tr": "Sınıflar arası çakışmalar",
        "description_tr": "Farklı sınıflara düşen ama çakışan veya kopya görünen örnekler.",
        "reader_goal": "Split ve etiket hatalarını görmek",
        "decision_importance": "prep_gate",
        "read_order": 34,
    },
    {
        "relative_path": "exact_duplicates.csv",
        "category": "review_items",
        "priority": "medium",
        "title_tr": "Exact duplicate listesi",
        "description_tr": "Aynı hash'e sahip görüntü gruplarını listeler.",
        "reader_goal": "Birebir kopyaları temizlemek",
        "decision_importance": "data_quality",
        "read_order": 35,
    },
]
